<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
    <!--  created with Free Online Sitemap Generator www.xml-sitemaps.com  -->
    <url>
        <loc>https://giftforpakistan.com</loc>
        <lastmod>2022-09-02T19:59:09+00:00</lastmod>
        <changefreq>weekly</changefreq>
        <priority>1.00</priority>
    </url>
    <url>
        <loc>https://giftforpakistan.com/blogs</loc>
        <lastmod>2022-09-02T19:59:09+00:00</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://giftforpakistan.com/about-us</loc>
        <lastmod>2022-09-02T19:59:09+00:00</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://giftforpakistan.com/login</loc>
        <lastmod>2022-09-02T19:59:09+00:00</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://giftforpakistan.com/order-tracking</loc>
        <lastmod>2022-09-02T19:59:09+00:00</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://giftforpakistan.com/email/verify</loc>
        <lastmod>2022-09-02T19:59:09+00:00</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://giftforpakistan.com/forgot-password</loc>
        <lastmod>2022-09-02T19:59:09+00:00</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://giftforpakistan.com/signup</loc>
        <lastmod>2022-09-02T19:59:09+00:00</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://giftforpakistan.com/terms-of-service</loc>
        <lastmod>2022-09-02T19:59:09+00:00</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://giftforpakistan.com/privacy-policy</loc>
        <lastmod>2022-09-02T19:59:09+00:00</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.80</priority>
    </url>
    <url>
        <loc>https://giftforpakistan.com/contact-us</loc>
        <lastmod>2022-09-02T19:59:09+00:00</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.80</priority>
    </url>
    @foreach ($posts as $post)
        <url>
            <loc>{{ url('/') }}/blog/{{ $post->slug }}</loc>
            <lastmod>{{ $post->created_at->tz('UTC')->toAtomString() }}</lastmod>
            <changefreq>weekly</changefreq>
            <priority>0.80</priority>
        </url>
    @endforeach
</urlset>